# Generated by Django 6.0.4 on 2026-04-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField()),
                ('tipo_solicitud', models.CharField(max_length=100)),
                ('orden_de_compra', models.IntegerField()),
                ('descripcion_solicitud', models.CharField(max_length=255)),
                ('id_solicitante', models.CharField(max_length=50)),
                ('id_user', models.CharField(max_length=50)),
                ('id_ingeniero', models.CharField(max_length=50)),
                ('id_activo', models.IntegerField()),
                ('ticket_entrega', models.CharField(max_length=100)),
                ('ticket_bodega', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=100)),
                ('observacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'registro_solicitudes',
                'managed': False,
            },
        ),
    ]
