# Generated by Django 6.0.4 on 2026-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('fecha_recepcion', models.DateField()),
                ('id_activo', models.IntegerField()),
                ('serie', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vehiculo_legal', models.CharField(max_length=100)),
                ('orden_compra', models.IntegerField()),
                ('categoria_reporte', models.CharField(max_length=100)),
                ('id_proveedor', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('rems', models.IntegerField()),
                ('hostname', models.CharField(max_length=50)),
                ('ticket_asignacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_bodega', models.CharField(blank=True, max_length=100, null=True)),
                ('entregado_a_usuario', models.CharField(max_length=50)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('id_user', models.CharField(max_length=50)),
                ('id_ingeniero', models.CharField(max_length=50)),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('ticket_devolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_devolucion', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ingeniero_devolucion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventario_total',
                'managed': False,
            },
        ),
    ]
