# Generated by Django 6.0.4 on 2026-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingenieros',
            fields=[
                ('id_ingeniero', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=225)),
                ('nivel', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ingenieros',
                'managed': False,
            },
        ),
    ]
