# Generated by Django 6.0.4 on 2026-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_activo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_activo', models.CharField(max_length=255)),
                ('categoria_activo', models.CharField(max_length=225)),
                ('marca', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('eovs', models.DateField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
    ]
