# Generated by Django 6.0.4 on 2026-04-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('vehiculo_legal', models.CharField(max_length=100)),
                ('goc', models.CharField(max_length=100)),
                ('empl_status', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('id_edificio', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('piso', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=100)),
                ('id_manager', models.CharField(max_length=50)),
                ('full_name_manager', models.CharField(max_length=255)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
