# Generated by Django 6.0.4 on 2026-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edificios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rems', models.IntegerField(db_index=True)),
                ('piso', models.CharField(blank=True, max_length=50)),
                ('area', models.CharField(max_length=150)),
                ('so_seats', models.IntegerField(blank=True, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=200)),
                ('x', models.FloatField(help_text='Posición X normalizada 0..1')),
                ('y', models.FloatField(help_text='Posición Y normalizada 0..1')),
            ],
            options={
                'db_table': 'mapa_area',
            },
        ),
        migrations.AlterModelOptions(
            name='edificios',
            options={'managed': False},
        ),
    ]
